# Generated by Django 3.0.7 on 2022-03-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_date', models.DateField(verbose_name='')),
                ('event_time', models.TimeField()),
                ('event_description', models.CharField(default='', max_length=1000)),
                ('event_price', models.IntegerField(default=0)),
                ('event_image', models.ImageField(default='', upload_to='events/images')),
            ],
        ),
    ]
