# Generated by Django 3.0.7 on 2022-03-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event',
            new_name='CollegeEvent',
        ),
    ]
